pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    squash: true
    experimental: true
    tags:
      - latest

  notify:
    image: plugins/downstream
    server: https://ci.toroid.io
    repositories:
      - drone-plugins/drone-kicad
    tags: [latest, 0.1.${DRONE_BUILD_NUMBER}]
    when:
      event: push
      success: true
      branch: master
