pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    registry: docker.io
    tags:
      - latest
    secrets: [docker_username, docker_password]
    when:
      branch: master

  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    registry: docker.io
    tags:
      - ${DRONE_BRANCH}
    secrets: [docker_username, docker_password]
    when:
      branch:
        exclude: [master]

  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-kicad
    secrets: [downstream_token]
    when:
      event: push
      status: success
      branch: master
