pipeline:
  publish:
    image: plugins/docker
    repo: toroid/kicad-base
    tags: [latest, 5.0.1]
    when:
      branch: master
      event: deployment
      environment: production
    secrets: [docker_username, docker_password]

  publish-test:
    image: plugins/docker
    repo: toroid/kicad-base
    tags: ${DRONE_DEPLOY_TO}
    when:
      event: deployment
      environment:
        exclude: production
    secrets: [docker_username, docker_password]
