pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    registry: docker.io
    tags:
      - latest
    secrets: [docker_username, docker_password]

  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-kicad
    tags: latest
    when:
      event: push
      status: success
      branch: master
