pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    registry: docker.io
    tags: [latest, 5.0.1]
    secrets: [docker_username, docker_password]

  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-kicad
    tags: latest
    secrets: [downstream_token]
    when:
      event: push
      status: success
      branch: master
