pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    squash: true
    experimental: true
    tags:
      - latest

  notify:
    image: plugins/downstream
    server: https://ci.toroid.io
    repositories:
      - ToroidDockerImages/kicad
    when:
      event: push
      success: true
      branch: master
