pipeline:
  docker:
    image: plugins/docker
    repo: toroid/kicad-base
    squash: true
    experimental: true
    tags:
      - latest

  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-kicad
    tags: latest
    when:
      event: push
      status: success
      branch: master
